### ISSUE TITLE
Installing BetaVQE

### ISSUE THREAD

**Issue by HamidArianZad** [wangleiphy/BetaVQE.jl#1]
Dear Yao managers,

I could almost install all parts of Yao on my system except BetaVQE.jl.
Actually, I get attached error. Could you please help me to resolve it?

![Julia_betaVQE](https://user-images.githubusercontent.com/97589591/150882779-80419a6c-dc52-4d27-a1bb-a5965687835f.png)

**Comment by wangleiphy** [comment]
@GiggleLiu Would you please have a look?

**Comment by GiggleLiu** [comment]
Thanks for the issue. I just updated the dependencies. It should work now. Please check the updated installation guide in README too.

**Comment by HamidArianZad** [comment]
Dear Jinguo,

Thank you very much I could install BetaVQE and test it normally.
Now, I am going to simulate the magnetization and specific heat of a particular 2D lattice in the presence of an external magnetic field as shown in below attached figure.

![MartiniLattices](https://user-images.githubusercontent.com/97589591/150972624-6e35304d-0bfa-4787-9d94-b1479f202b49.png)

I want to follow the procedure that you have used in your publication Mach. Learn.: Sci. Technol. 2 (2021) 025011 for 3x3 lattice.
Please let me know what is the starting point to do that and the steps from starting to executing code. 
Thanks!!

**Comment by wangleiphy** [comment]
I would imagine the first step is to get the Hamiltonian and the lattice right. For that, you may start by modifying these codes:  
https://github.com/wangleiphy/BetaVQE.jl/blob/master/src/hamiltonian.jl
