### ISSUE TITLE
Solving 2D kagome lattice with BetaVQE.jl

### ISSUE THREAD

**Issue by HamidArianZad** [wangleiphy/BetaVQE.jl#2]
Dear BetaVQE group,

I would like to solve a Heisenberg XXX model on a 2D kagome lattice with more than 24 sites by using BetaVQE. The model is considered in the presence of a longitudinal magnetic field. Then I would like to obtain some results for the magnetization versus magnetic field at low temperature. To do so, I installed julia, Yao.jl, YaoExtention.jl, and BetaVQE.jl. 
Could you please let me know from where I have to begin to introduce my model to your package more efficiently? As the sample model in Fig. 2 of your publication Mach. Learn.: Sci. Technol. 2 (2021) 025011.
And could you let me have your sample code by which you simulated Fig. 4 in Mach. Learn.: Sci. Technol. 2 (2021) 025011?

**Comment by wangleiphy** [comment]
Thanks for your interests. 

Q1: please see this https://github.com/wangleiphy/BetaVQE.jl/issues/1#issuecomment-1021280341 

Q2: To reproduce that figure, you can simply run the code following instructions in the README of this repo.
