### ISSUE TITLE
How can I change hamiltonian?

### ISSUE THREAD

**Issue by akio-tomiya** [wangleiphy/BetaVQE.jl#4]
Hi

I would like to use the betaVQE on a different system.
Which part should I change?
I plan to apply it on a Heisenberg type but different system.

**Comment by wangleiphy** [comment]
Thanks!

Here are a few examples of defining Hamiltonians

https://github.com/wangleiphy/BetaVQE.jl/blob/master/src/hamiltonian.jl

**Comment by akio-tomiya** [comment]
Thanks for quick reply!
If I understand correctly, this is the only part I change when I apply beta-VQE to another spin system, right?

**Comment by wangleiphy** [comment]
Right!  
In your applications you can build your hamiltonian like this, 
https://github.com/wangleiphy/BetaVQE.jl/blob/master/runner.jl#L48 

then feed it into the `train` function of BetaVQE

**Comment by akio-tomiya** [comment]
Thanks. I have another question. How can I make figure 4 in the paper?
Figures for observables along with beta. After training, I assume that I have trained weights/parameters in a JLD file.
Should I load JLD file in other application and calculate something?
Sorry for continuous posting.

**Comment by wangleiphy** [comment]
Physical observables will be stored together with trained weights, see this line
https://github.com/wangleiphy/BetaVQE.jl/blob/master/runner.jl#L106

You can load the `jld` file in another script for plotting, for example

```python 
import h5py 
h5file = h5py.File('data.jld2')
f, e, s, cv, gamma = h5file['result'][()]
print (f, e, s, cv, gamma)
h5file.close()
```

**Comment by akio-tomiya** [comment]
I see, thanks. Now I understand how the code works.
