### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by akio-tomiya** [wangleiphy/BetaVQE.jl#5]
Hi

I attempt execute the code (without any modification) but it does not work.
All of the tests have been passed.

I tried 2 OS and 3 versions of Julia
1. Julia 1.7.2 on Ubuntu and Apple silicon 
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.2.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)

2. Julia 1.6 and 1.6.6 on Ubuntu
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) W-2265 CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cascadelake)

The error message is as follows,
```
$ julia --project runner.jl learn 2 2 2.0 2.0
ERROR: LoadError: ArgumentError: Package JLD2 does not have OrderedCollections in its dependencies:
- If you have JLD2 checked out for development and have
  added OrderedCollections as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with JLD2
Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:884
 [2] include
   @ ./Base.jl:386 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1213
 [4] top-level scope
   @ none:1
 [5] eval
   @ ./boot.jl:360 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude ./client.jl:446
 [7] top-level scope
   @ none:1
in expression starting at /home/akio/.julia/packages/JLD2/k9Gt0/src/JLD2.jl:1
ERROR: LoadError: Failed to precompile JLD2 [033835bb-8acc-5ee8-8aae-3f567f8a3819] to /home/akio/.julia/compiled/v1.6/JLD2/jl_veIVCd.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
   @ Base ./loading.jl:1360
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1306
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1021
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:914
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:901
in expression starting at /home/akio/.julia/dev/BetaVQE/runner.jl:2
```
All error messages are same.
Julia has been installed though Jill. 

What kind of environment do you assume? 
Thank you in advance.

**Comment by akio-tomiya** [comment]
I solved the problem partially.
I added following packages:

- OrderedCollections
- IrrationalConstants
- LLVM
- GenericSchur

And, the package starts working with a lot of warnings.

**Comment by GiggleLiu** [comment]
Please check the latest master. You can remove the legacy VAN installation now, because we have merged it into this repo as a submodule for better maintainance.

Let me know it you still have issues running the example.
